In [10]:
import pandas as pd
import numpy as np
import os

df1 = pd.read_csv("car.csv", error_bad_lines=False)
df2 = pd.read_csv("JAE.csv", error_bad_lines=False,encoding = 'unicode_escape')
df3 = pd.read_csv("JAR.csv", error_bad_lines=False)
df3=df3.rename(columns={'article_name ':'article_name'})
df = pd.concat([df1, df2, df3], axis=1)
df.to_csv('df.csv')
a = list(set(df.columns))
#print(a)
resu = pd.DataFrame(columns=a)
Res=pd.concat([df1,resu,df2,df3],axis=0)
Res.to_csv('Res.csv')
pd.set_option('display.max_columns',25)
#Res.set_index('article_name',inplace=True)
Res = Res.replace(np.nan,"",regex=True)
Res['author'] =Res['author1'] + "," + Res['author2'] +"," +  Res['author4'] +"," + Res['author3'] +"," + Res['authors']+"," + Res['article_authors']
Res['institute']=Res['institute1'] +',' + Res['institute2']+ ',' + Res['institute3'] + "," + Res['institute4']
Res['volume']=Res['volume_issue'] +',' + Res['volumes']+ ',' + Res['subvolumes'] + "," + Res['subvolumes-href']
Res["Date"] = Res['publication_date']+','+Res['publication_year']
Res.drop(columns=['author3', 'volumes', 'article_title', 'article_authors', 'institute4', 'publication_year', 'version', 'institute3', 'institute2', 'author4', 'publication_date', 'subvolumes', 'institute1', 'subvolumes-href', 'author2', 'volume_issue', 'author1', 'authors', 'volumes-href'],inplace=True)
#Res.head(3)
Tf=Res
Tf['colm']=Tf['article_name']+','+ Tf['journal_name']+','+Tf['author']+","+Tf['institute']+ ","+Tf['volume']+','+Tf['Date']
Tf.drop(columns=['article_name','journal_name','author','institute','volume','Date'],inplace=True)
Tf.head(3)

b'Skipping line 566: expected 12 fields, saw 23\n'
C:\Users\Maheep Chaudhary\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


colm
0  Terborgh's asset replacement formula reconside...
1  John Butterworth's pioneering contributions to...
2  On the value and limitations of financial acco...

In [11]:
import re, math
from collections import Counter
a=np.zeros([2860,21])
#print(a)

WORD = re.compile(r'\w+')

def get_cosine(vec1, vec2):
     intersection = set(vec1.keys()) & set(vec2.keys())
     numerator = sum([vec1[x] * vec2[x] for x in intersection])

     sum1 = sum([vec1[x]**2 for x in vec1.keys()])
     sum2 = sum([vec2[x]**2 for x in vec2.keys()])
     denominator = math.sqrt(sum1) * math.sqrt(sum2)

     if not denominator:
        return 0.0
     else:
        return float(numerator) / denominator

def text_to_vector(Text):
     words = WORD.findall(Text)
     return Counter(words)
for i in range(0,2860):
    for j in range(0,21):
        vector1 = text_to_vector(Tf.iloc[i,-1])
        vector2 = text_to_vector(Tf.iloc[j,-1])
        a[i][j] = get_cosine(vector1, vector2)

print(a)

[[1.         0.6011334  0.60942528 ... 0.55555556 0.54433105 0.5       ]
 [0.6011334  1.         0.68499578 ... 0.5062176  0.55217628 0.5220369 ]
 [0.60942528 0.68499578 1.         ... 0.57735027 0.61871843 0.60140653]
 ...
 [0.20739034 0.2952693  0.3592106  ... 0.27652045 0.34925035 0.31108551]
 [0.17010345 0.23249528 0.26516504 ... 0.23814484 0.34375    0.25515518]
 [0.16265001 0.19451951 0.25354628 ... 0.26024002 0.26892644 0.24397502]]


In [12]:
#s = int(input())
s=9
m={}
l=[]
#print(a[1,s])
for i in range(0,100):
    m[i]=a[i,s]
    l.append(a[i,s])
l.sort(reverse=True)
del(l[0])
for p in l:
    for k,v in m.items():
        if v==p:
            print("The Recommended paper are as follows:",k)

The Recommended paper are as follows: 2
The Recommended paper are as follows: 64
The Recommended paper are as follows: 17
The Recommended paper are as follows: 49
The Recommended paper are as follows: 27
The Recommended paper are as follows: 93
The Recommended paper are as follows: 35
The Recommended paper are as follows: 44
The Recommended paper are as follows: 13
The Recommended paper are as follows: 97
The Recommended paper are as follows: 47
The Recommended paper are as follows: 4
The Recommended paper are as follows: 19
The Recommended paper are as follows: 4
The Recommended paper are as follows: 19
The Recommended paper are as follows: 46
The Recommended paper are as follows: 15
The Recommended paper are as follows: 8
The Recommended paper are as follows: 22
The Recommended paper are as follows: 12
The Recommended paper are as follows: 61
The Recommended paper are as follows: 58
The Recommended paper are as follows: 42
The Recommended paper are as follows: 20
The Recommended pape